version: '3.8'

services:
  # Backend Development Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: crud-backend-dev
    environment:
      # Database configuration (external database)
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/inference_instances_dev}
      DATABASE_HOST: ${DATABASE_HOST:-localhost}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-inference_instances_dev}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      ENVIRONMENT: development
      DEBUG: true
      LOG_LEVEL: DEBUG
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    networks:
      - dev-network
    volumes:
      - .:/app
      - /app/venv
      - ./logs:/app/logs
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crud-frontend-dev
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
      - "${VITE_PORT:-5173}:5173"
    depends_on:
      - backend
    networks:
      - dev-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    restart: unless-stopped

networks:
  dev-network:
    driver: bridge