CREATE TABLE inference_instances(
    id SERIAL NOT NULL,
    name varchar(255) NOT NULL,
    model_name varchar(255) NOT NULL,
    cluster_name varchar(255) NOT NULL,
    pp integer,
    cp integer,
    n_workers integer,
    replicas integer,
    priorities json,
    "desc" varchar(1024),
    separate_video_encode boolean,
    separate_video_decode boolean,
    separate_t5_encode boolean,
    vae_store_type varchar(50),
    t5_store_type varchar(50),
    enable_cuda_graph boolean,
    task_concurrency integer,
    celery_task_concurrency integer,
    status varchar(50),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    image_tag varchar(50) DEFAULT 'latest'::character varying,
    nonce varchar(50),
    tp integer DEFAULT 1,
    checkpoint_path varchar,
    ephemeral boolean,
    ephemeral_to varchar,
    ephemeral_from varchar,
    ephemeral_min_period_seconds integer,
    envs json,
    model_version varchar,
    pipeline_mode varchar,
    quant_mode boolean,
    distill_mode boolean,
    m405_mode boolean,
    fps integer DEFAULT 24,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX inference_instances_name_key ON public.inference_instances USING btree (name);